services:
  postgres:
    image: postgres:15
    container_name: sistemavoucher_postgres
    environment:
      POSTGRES_DB: sistemavoucher_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sistemavoucher_network

  adminer:
    image: adminer
    container_name: sistemavoucher_adminer
    ports:
      - "8085:8085"
    networks:
      - sistemavoucher_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  sistemavoucher_network:
    driver: bridge